#!/bin/bash -e
 
PROJECT="$(basename '`pwd`')"
BUCKET="jenkins-terraform-test"
REGION="ap-southeast-2"
 
init() {
  if [ -d .terraform ]; then
    if [ -e .terraform/terraform.tfstate ]; then
      echo "Remote state already exist!"
      if [ -z $IGNORE_INIT ]; then
        exit 1
      fi
    fi
  fi
 
  cat << EOF > remote.tf
terraform {
  backend "s3" {
    bucket = "${BUCKET}"
    key    = "${PROJECT}"
    region = "${REGION}"
  }
}
EOF
}
 
while getopts "i" opt; do
  case "$opt" in
    i)
      IGNORE_INIT="true"
      ;;
  esac
done
 
shift $((OPTIND-1))
 
init

